# Generated by Django 3.0.3 on 2020-03-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodos', '0002_auto_20200309_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytodosmodel',
            name='content',
            field=models.TextField(default='nothing'),
        ),
        migrations.AlterField(
            model_name='mytodosmodel',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
